add filter that returns an error for the rpc is the filter is malformed
helius-labs/agave pull request #9
Opened 2024-12-31 20:12 UTC by jeffhelius

#### Problem
Root cause appears to be:
    -Customer(s) send gPA queries on Tokenkeg with an invalid filter
    -RPC code ignores the filter
    -RPC returns all tokenkeg accounts
    -Node dies

#### Summary of Changes
- Added code to prematurely check if the filter for getProgramAccounts is malformed. If it is, it returns a jsonrpc error instead of continuing on with the query omitting the filter

Fixes #

Test

### improper filter
curl \
        -X POST \
        -H "Content-Type: application/json" \
        -d '{
      "jsonrpc": "2.0",
      "id": 1,
      "method": "getProgramAccounts",
      "params": [
        "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        {
          "encoding": "jsonParsed",
          "filters": [
            { "dataSize": 200 }
          ]
        }
      ]
    }' \
        http://127.0.0.1:8899/
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid SPL token data size filter. Expected 165, got 200"},"id":1}

### no filter
curl \
        -X POST \
        -H "Content-Type: application/json" \
        -d '{
      "jsonrpc": "2.0",
      "id": 1,
      "method": "getProgramAccounts",
      "params": [
        "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        {
          "encoding": "jsonParsed"
        }
      ]
    }' \
        http://127.0.0.1:8899/
{"jsonrpc":"2.0","result":[],"id":1}

2024-12-31 21:20 UTC, NicolasPennie commented
The no filter should fail on a deployed node with the account index for tokenkeg excluded

2024-12-31 21:22 UTC, NicolasPennie requested changes

2024-12-31 21:22 UTC, NicolasPennie commented on rpc/src/rpc.rs
> +fn verify_spl_token_owner_filters(
We should do this for spl_token_mint_filters too

2024-12-31 21:22 UTC, NicolasPennie commented on rpc/src/rpc.rs
> +        verify_spl_token_owner_filters(program_id, &filters)?;
Can we perform the validation within the `get_filters` instead?

2025-01-02 12:08 UTC, jeffhelius commented on rpc/src/rpc.rs
> +        verify_spl_token_owner_filters(program_id, &filters)?;
yes, moved

2025-01-02 12:08 UTC, jeffhelius commented on rpc/src/rpc.rs
> +fn verify_spl_token_owner_filters(
yes

2025-01-02 12:16 UTC, merged